"""initial schema

Revision ID: ee1143141713
Revises: 
Create Date: 2026-06-13 10:32:31.357603
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee1143141713'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('equipment_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'model', name='uq_type_category_model')
    )
    op.create_table('label_sizes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('height_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=False),
    sa.Column('zpl_template', sa.Text(), nullable=False),
    sa.Column('barcode_type', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_op_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=26), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('conflict_detail', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_op_id')
    )
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'code', name='uq_lab_country_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_user_provider_external'),
    sa.UniqueConstraint('username')
    )
    op.create_table('consecutives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('current_value', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'laboratory_id', name='uq_seq_country_lab')
    )
    op.create_table('equipment_tags',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('serial_code', sa.String(length=60), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('consecutive', sa.BigInteger(), nullable=False),
    sa.Column('random_code', sa.String(length=12), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('client_op_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_op_id'),
    sa.UniqueConstraint('country_code', 'laboratory_id', 'consecutive', name='uq_tag_country_lab_consec'),
    sa.UniqueConstraint('serial_code')
    )
    op.create_table('serial_formats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('laboratory_id', sa.Integer(), nullable=True),
    sa.Column('template', sa.String(length=120), nullable=False),
    sa.Column('random_length', sa.Integer(), nullable=False),
    sa.Column('random_alphabet', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.String(length=26), nullable=False),
    sa.Column('event', sa.String(length=20), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.String(length=26), nullable=False),
    sa.Column('label_size_id', sa.Integer(), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('darkness', sa.Integer(), nullable=False),
    sa.Column('zpl_generated', sa.Text(), nullable=False),
    sa.Column('is_reprint', sa.Boolean(), nullable=False),
    sa.Column('printed_by', sa.Integer(), nullable=True),
    sa.Column('printed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_tags.id'], ),
    sa.ForeignKeyConstraint(['label_size_id'], ['label_sizes.id'], ),
    sa.ForeignKeyConstraint(['printed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_jobs')
    op.drop_table('equipment_status_history')
    op.drop_table('serial_formats')
    op.drop_table('equipment_tags')
    op.drop_table('consecutives')
    op.drop_table('users')
    op.drop_table('laboratories')
    op.drop_table('sync_log')
    op.drop_table('roles')
    op.drop_table('label_sizes')
    op.drop_table('equipment_types')
    op.drop_table('countries')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
